- name: Deploy on server
  uses: appleboy/ssh-action@v1
  with:
    host: ${{ secrets.SERVER_HOST }}
    username: ${{ secrets.SERVER_USER }}
    key: ${{ secrets.SERVER_SSH_KEY }}
    # 디버그/타임아웃(선택)
    debug: true
    command_timeout: 15m
    # GitHub env를 원격 스크립트에 전달할 목록
    envs: DB_CONFIG_JSON
    script: |
      set -e  # v1에서 script_stop 대체
      APP_DIR="/home/${{ secrets.SERVER_USER }}/app"
      JAR_NAME="test-api.jar"
      LOG_FILE="$APP_DIR/app.log"

      mkdir -p "$APP_DIR"

      # 1) 이전 프로세스 종료(없으면 무시)
      pkill -f "$JAR_NAME" || true
      sleep 3

      # 2) 백그라운드 기동: 세션과 완전히 분리
      echo "애플리케이션 재시작..."
      nohup java -jar "$APP_DIR/$JAR_NAME" --spring.profiles.active=prod \
        </dev/null >> "$LOG_FILE" 2>&1 & disown || true

      # 3) 헬스체크 (성공 시 0으로 명시 종료)
      echo "헬스체크 시작..."
      for i in {1..10}; do
        if curl -fsS https://h-infinite-power.store/test-api/health; then
          echo "✅ 애플리케이션이 정상적으로 시작되었습니다."
          exit 0
        fi
        echo "헬스체크 실패, 재시도 중... ($i/10)"
        sleep 10
      done

      echo "❌ 애플리케이션 시작 실패"
      tail -n 200 "$LOG_FILE" || true
      exit 1
